# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackYourFinances' do
  use_frameworks!

  pod 'Charts'
  pod 'CalendarKit'
  pod 'IQKeyboardManagerSwift'
  
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'

  pod 'KeychainAccess'
end
